parameters:
  - name: workingDirectory
    displayName: Current working directory
    type: string

  - name: image
    displayName: Image repository
    type: string

jobs:
  - job: ${{ parameters.image }}
    displayName: Build and push Docker image for ${{ parameters.image }}
    steps:
      - task: Docker@2
        displayName: Login to Docker Hub
        inputs:
          command: login
          containerRegistry: dockerHub
      - task: Docker@2
        displayName: Build the image
        inputs:
          command: buildAndPush
          buildContext: ${{ parameters.workingDirectory }}
          repository: ${{ parameters.image }}
          tags: |
            latest
            $(Build.BuildId)